"""create movie table

Revision ID: 8b558433244a
Revises: 
Create Date: 2024-02-09 13:20:22.487023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b558433244a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('year', sa.String(length=150), nullable=False),
    sa.Column('rated', sa.String(length=150), nullable=False),
    sa.Column('runtime', sa.String(length=150), nullable=False),
    sa.Column('released', sa.String(length=150), nullable=False),
    sa.Column('genre', sa.String(length=150), nullable=False),
    sa.Column('director', sa.String(length=150), nullable=False),
    sa.Column('writer', sa.String(length=250), nullable=False),
    sa.Column('actors', sa.String(length=250), nullable=False),
    sa.Column('plot', sa.String(length=2000), nullable=False),
    sa.Column('language', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('awards', sa.String(length=150), nullable=False),
    sa.Column('poster', sa.String(length=1000), nullable=False),
    sa.Column('ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metascore', sa.String(length=150), nullable=False),
    sa.Column('imdb_rating', sa.String(length=150), nullable=False),
    sa.Column('imdb_votes', sa.String(length=150), nullable=False),
    sa.Column('imdb_id', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=150), nullable=False),
    sa.Column('dvd', sa.String(length=150), nullable=False),
    sa.Column('box_office', sa.String(length=150), nullable=False),
    sa.Column('production', sa.String(length=150), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=False),
    sa.Column('response', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
