"""create movie table

Revision ID: afa553c2bad6
Revises: 
Create Date: 2024-02-07 14:49:22.163858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afa553c2bad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('year', sa.String(length=150), nullable=False),
    sa.Column('rated', sa.String(length=150), nullable=False),
    sa.Column('runtime', sa.String(length=150), nullable=False),
    sa.Column('genre', sa.String(length=150), nullable=False),
    sa.Column('director', sa.String(length=150), nullable=False),
    sa.Column('writer', sa.String(length=250), nullable=False),
    sa.Column('actors', sa.String(length=250), nullable=False),
    sa.Column('plot', sa.String(length=150), nullable=False),
    sa.Column('language', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('awards', sa.String(length=150), nullable=False),
    sa.Column('poster', sa.String(length=450), nullable=False),
    sa.Column('ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metascore', sa.String(length=150), nullable=False),
    sa.Column('imdb_rating', sa.String(length=150), nullable=False),
    sa.Column('imdb_votes', sa.String(length=150), nullable=False),
    sa.Column('imdb_id', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=150), nullable=False),
    sa.Column('total_seasons', sa.String(length=150), nullable=False),
    sa.Column('response', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
